USE [Golab]
GO

/****** Object:  Table [dbo].[GOLAB_CadFuncionario]    Script Date: 09/24/2020 23:46:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GOLAB_CADFUNCIONARIO](
	[MATRICULA] [varchar](20) NOT NULL,
	[NOMEFUNC] [varchar](50) NOT NULL,
	[FUNCAO] [varchar](50) NULL,
	[DTADMISSAO] [datetime] NULL,
	[DTDEMISSAO] [datetime] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[GOLAB_CadUser]    Script Date: 09/24/2020 23:46:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GOLAB_CADUSER](
    [ID_CADUSER] [int] IDENTITY(1,1) NOT NULL,
	[USERMATRICULA] [varchar](20) NOT NULL,
	[SENHA] [int] NOT NULL,
	[FUNCAO] [varchar](50) NOT NULL,
	[ATIVO] [char](1) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[GOLAB_ALIQUOTAIMP]    Script Date: 09/24/2020 23:46:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GOLAB_ALIQUOTAIMP](
	[ID_IMP] [int] IDENTITY(1,1) NOT NULL,
	[SIGLA_IMP] [varchar](6) NOT NULL,
	[DT_CADASTRO] [datetime] DEFAULT getdate(),
	[DESC_IMP] [varchar](30) NULL,
	[PERC_IMP] [numeric](5, 2) NOT NULL,
	[ATIVO] [char](1) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[GOLAB_POSTO]    Script Date: 09/24/2020 23:46:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GOLAB_POSTO](
    [CNPJ_POSTO] [varchar](20) NOT NULL,
	[RAZAOSOCIAL] [varchar](80) NOT NULL,
	[NOMEFANTASIA] [varchar](80) NULL,
	[ENDERECO] [varchar](80) NULL,
	[CEP] [varchar](8) NULL,
	[RESPTECNICO] [varchar](80) NULL,	
	[REGISTRO] [varchar](8) NULL,		
	[TEL] [varchar](12) NULL,
	[EMAIL] [varchar](80) NULL,
	[GERENTE] [varchar](20) NULL
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[GOLAB_CADBOMBA]    Script Date: 09/24/2020 23:46:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GOLAB_CADBOMBA](
	[ID_BOMBA] [int] IDENTITY(1,1) NOT NULL,
	[DESC_BOMBA] [varchar](30) NOT NULL,
	[LOCAL_BOMBA] [varchar](80) NOT NULL,
	[NUMSERIE_BOMBA] [varchar](10) NOT NULL,
	[POSTO] [varchar](20) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[GOLAB_BICO]    Script Date: 09/24/2020 23:46:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GOLAB_BICO](
	[BICO] [int] NOT NULL,
	[ID_BOMBA] [int] NOT NULL,
	[ID_COMBUSTIVEL] [int] NOT NULL,
    [VALOR_LITRO] [numeric](5, 3) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[GOLAB_TIPOCOMBUSTIVEL]    Script Date: 09/24/2020 23:46:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GOLAB_TIPOCOMBUSTIVEL](
	[ID_COMBUSTIVEL] [int] IDENTITY(1,1) NOT NULL,
	[TIPO] [varchar](30) NOT NULL,
	[DESCRICAO] [varchar](80) NULL,
	
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[GOLAB_FORMAPGTO]    Script Date: 09/24/2020 23:46:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GOLAB_FORMAPGTO](
	[ID_FORMAPGTO] [int] IDENTITY(1,1) NOT NULL, 
	[FORMAPGTO] [varchar](30) NOT NULL,
	[DESC_FORMAPGTO] [varchar](80) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[GOLAB_MVT]    Script Date: 09/24/2020 23:46:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GOLAB_MVT_CAB](
	[IDC_MVT] [int] IDENTITY(1,1) NOT NULL,
	[MVTC_DT_MOV] [datetime] NOT NULL,
	[VALOR_MVT] [numeric](18, 3) NULL,
	[VALOR_IMPOSTO] [numeric](18, 3) NULL,
	[VALOR_MVT_TOTAL] [numeric](18, 3) NULL,
	[MAT_FRENTISTA] [varchar](20) NOT NULL,
	[ID_FORMAPGT] [int] NULL
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[GOLAB_MVT_DET](
	[IDD_MVT] [int] IDENTITY(1,1) NOT NULL,
	[IDC_MVT] [int] NOT NULL,
	[MVTD_DT_MOV] [datetime] NOT NULL,
	[BICO] [int] NOT NULL,
	[ID_BOMBA] [int] NOT NULL,	
	[VALOR_LITRO] [numeric](18, 3) NULL,
	[QTDE_MVT] [numeric](18, 3) NULL,
	[VALOR_MVT] [numeric](18, 3) NULL,
	[VALOR_IMPOSTO] [numeric](18, 2) NULL,
	[VALOR_MVT_TOTAL] [numeric](18, 2) NULL,
	[MAT_FRENTISTA] [varchar](20) NULL,
	[ID_FORMAPGTO] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF

GO


/* ADCIONAR AS CHAVES */
ALTER TABLE GOLAB_CADFUNCIONARIO
ADD CONSTRAINT PK_CADFUNCIONARIO PRIMARY KEY (MATRICULA);

GO

ALTER TABLE GOLAB_CADUSER
ADD CONSTRAINT PK_CADUSER PRIMARY KEY (ID_CADUSER,USERMATRICULA);

GO

ALTER TABLE GOLAB_ALIQUOTAIMP
ADD CONSTRAINT PK_ALIQUOTAIMP PRIMARY KEY (ID_IMP);

GO

ALTER TABLE GOLAB_POSTO
ADD CONSTRAINT PK_POSTO PRIMARY KEY (CNPJ_POSTO);

GO

ALTER TABLE GOLAB_CADBOMBA
ADD CONSTRAINT PK_CADBOMBA PRIMARY KEY (ID_BOMBA);

GO

ALTER TABLE GOLAB_BICO
ADD CONSTRAINT PK_BICO PRIMARY KEY (BICO,ID_BOMBA);

GO

ALTER TABLE GOLAB_TIPOCOMBUSTIVEL
ADD CONSTRAINT PK_TIPOCOMBUSTIVEL PRIMARY KEY (ID_COMBUSTIVEL);

GO

ALTER TABLE GOLAB_FORMAPGTO
ADD CONSTRAINT PK_FORMAPGTO PRIMARY KEY (ID_FORMAPGTO);

GO

/*ALTER TABLE GOLAB_FORMAPGTO
ADD CONSTRAINT PK_FORMAPGTO PRIMARY KEY (ID_FORMAPGTO);

GO*/

ALTER TABLE GOLAB_MVT_CAB
ADD CONSTRAINT PK_MVT_CAB PRIMARY KEY (IDC_MVT);

GO

ALTER TABLE GOLAB_MVT_DET
ADD CONSTRAINT PK_MVT_DET PRIMARY KEY (IDD_MVT,IDC_MVT);
/********************FIM PRIMARY KEY*********************/

/*Adicionar integrridade referencial entre as tabelas */
GO

ALTER TABLE GOLAB_CADUSER
   ADD CONSTRAINT FK_CADUSER FOREIGN KEY (USERMATRICULA)
      REFERENCES GOLAB_CADFUNCIONARIO (MATRICULA)
      ON DELETE CASCADE
      ON UPDATE CASCADE
 
GO

ALTER TABLE GOLAB_BICO
   ADD CONSTRAINT FK_BICO FOREIGN KEY (ID_BOMBA)
      REFERENCES GOLAB_CADFUNCIONARIO (MATRICULA)
      ON DELETE CASCADE
      ON UPDATE CASCADE
   
/*
ALTER TABLE COSMOFL..MVENTR_VOUCHER_DEV
   ADD CONSTRAINT FK_MVENTR_VOUCHER_DEV FOREIGN KEY (MVCH_DT_MOV,MVCH_CD_FILIAL_MOV,MVCH_NR_ECF_MOV)
      REFERENCES COSMOSFL..MVENT_TRCDEV_CAB (MVTC_DT_MOV,MVTC_CD_FILIAL_MOV,MVTC_NR_ECF_MOV)
      ON DELETE CASCADE
      ON UPDATE CASCADE   */   
      
/******************************************** FIM*******************************************/

/**********************/
/*
DROP TABLE [GOLAB_MVT]
DROP TABLE [GOLAB_FORMAPGTO]
DROP TABLE [GOLAB_TIPOCOMBUSTIVEL]
DROP TABLE [GOLAB_BICO]
DROP TABLE [GOLAB_CADBOMBA]
DROP TABLE [GOLAB_POSTO]
DROP TABLE [GOLAB_ALIQUOTAIMP]
DROP TABLE [GOLAB_CADUSER]
DROP TABLE [GOLAB_CADFUNCIONARIO]
DROP TABLE [GOLAB_POSTO]
DROP TABLE [GOLAB_MVT_CAB]
DROP TABLE [GOLAB_MVT_DET]
*/

/* 
select * from GOLAB_MVT_CAB --where FUNCAO LIKE '%FRENTISTA%'
select * from GOLAB_MVT_DET

 select DET.IDD_MVT AS ITEM,
       DET.BICO BOMBA,
       CAB.MVTC_DT_MOV DATAMOVIMENTO,
       DET.VALOR_LITRO PRECOPORLITRO,
       DET.QTDE_MVT QTDE_ABASTECIDA,
       DET.VALOR_MVT VL_ABASTECIMENTO,
       DET.VALOR_IMPOSTO VL_IMPOSTO
	from GOLAB_MVT_CAB CAB
inner join GOLAB_MVT_DET DET on CAB.IDC_MVT = DET.IDC_MVT 
                            and CAB.MVTC_DT_MOV = DET.MVTD_DT_MOV
where CAB.MVTC_DT_MOV >= '2020-09-30' AND CAB.MVTC_DT_MOV <= '2020-09-30'

select F.MATRICULA, F.NOMEFUNC, F.FUNCAO, U.ATIVO from GOLAB_CADFUNCIONARIO F
INNER JOIN GOLAB_CADUSER U ON U.USERMATRICULA = F.MATRICULA

select B.BICO, C.TIPO, BB.DESC_BOMBA, B.VALOR_LITRO, BB.POSTO from GOLAB_BICO B
inner join GOLAB_CADBOMBA BB ON B.ID_BOMBA = BB.ID_BOMBA
inner join GOLAB_TIPOCOMBUSTIVEL C ON B.ID_COMBUSTIVEL = C.ID_COMBUSTIVEL

*/
/****** inserindo dados para movimentação */
/*INSERT INTO [Golab].[dbo].[GOLAB_MVT_CAB]
           ([MVTC_DT_MOV]
           ,[VALOR_MVT]
           ,[VALOR_IMPOSTO]
           ,[VALOR_MVT_TOTAL]
           ,[MAT_FRENTISTA]
           ,[ID_FORMAPGT])
     VALUES
           (GETDATE(),100.000,13.000,87.000,'046.543.213-14',1)*/
           
           go

/*INSERT INTO [Golab].[dbo].[GOLAB_MVT_DET]
           ([IDC_MVT]
           ,[MVTD_DT_MOV]
           ,[BICO]
           ,[ID_BOMBA]
           ,[VALOR_LITRO]
           ,[QTDE_MVT]
           ,[VALOR_MVT]
           ,[VALOR_IMPOSTO]
           ,[VALOR_MVT_TOTAL]
           ,[MAT_FRENTISTA]
           ,[ID_FORMAPGTO])
     VALUES
           (1,'2020-09-29 22:32:58.633',90909,1,3.899,25.648,100.000,13.000,87.000,'045.543.213-14',1)
           (<IDC_MVT, int,>
           ,<MVTD_DT_MOV, datetime,>
           ,<BICO, int,>
           ,<ID_BOMBA, int,>
           ,<VALOR_LITRO, numeric(5,3),>
           ,<QTDE_MVT, numeric(5,3),>
           ,<VALOR_MVT, numeric(5,3),>
           ,<VALOR_IMPOSTO, numeric(5,2),>
           ,<VALOR_MVT_TOTAL, numeric(5,2),>
           ,<MAT_FRENTISTA, varchar(20),>
           ,<ID_FORMAPGTO, int,>)*/
           
       /******FIM SCRIPT INSERIR DADOS**************/
       
      